service: streams

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    STREAMS: ${self:service}-${opt:stage, self:provider.stage}
    ACTIVE_STREAMS: active-${self:service}-${opt:stage, self:provider.stage}
    MAX_STREAMS: 3
    TTL: 60
  defaults:
    stage: dev
    region: us-east-1

package:
  individually: true
  exclude:
    - lib/**
    - functions/**

custom:
  webpackIncludeModules: true,
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/dynamodbSchema

functions:
  open-stream:
    handler: src/functions/open-stream/index.run
    events:
      - http:
          method: POST
          path: v1/open-stream

  ping-stream:
    handler: src/functions/ping-stream/index.run
    events:
      - http:
          method: POST
          path: v1/ping-stream

  close-stream:
    handler: src/functions/close-stream/index.run
    events:
      - http:
          method: POST
          path: v1/close-stream